// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG3tQzScc2uQ2ojhwNrVcyXMvVgpDK3Nk',
    appId: '1:103040357760:web:179edd8eab46c807a11d65',
    messagingSenderId: '103040357760',
    projectId: 'housewalls',
    authDomain: 'housewalls.firebaseapp.com',
    storageBucket: 'housewalls.appspot.com',
    measurementId: 'G-QR3PLL8VYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWWgx69Pig3K6br3MI90xb9S0PZN8JiFY',
    appId: '1:103040357760:android:a6be31b58ce58ee5a11d65',
    messagingSenderId: '103040357760',
    projectId: 'housewalls',
    storageBucket: 'housewalls.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEoKXIwp8fEvXUCJUHuiedH5HFBWTHRGY',
    appId: '1:103040357760:ios:3a79967ed2c356baa11d65',
    messagingSenderId: '103040357760',
    projectId: 'housewalls',
    storageBucket: 'housewalls.appspot.com',
    iosBundleId: 'com.example.houseWalls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEoKXIwp8fEvXUCJUHuiedH5HFBWTHRGY',
    appId: '1:103040357760:ios:3a79967ed2c356baa11d65',
    messagingSenderId: '103040357760',
    projectId: 'housewalls',
    storageBucket: 'housewalls.appspot.com',
    iosBundleId: 'com.example.houseWalls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG3tQzScc2uQ2ojhwNrVcyXMvVgpDK3Nk',
    appId: '1:103040357760:web:3fdb6a6448eceb81a11d65',
    messagingSenderId: '103040357760',
    projectId: 'housewalls',
    authDomain: 'housewalls.firebaseapp.com',
    storageBucket: 'housewalls.appspot.com',
    measurementId: 'G-B5ZFK24MT0',
  );
}
